FROM resin/%%RESIN_MACHINE_NAME%%-golang

#ENV INITSYSTEM on

RUN apt-get update
#apt-get install -y build-essential python-dev python-smbus python-pip
RUN rm -rf /var/lib/apt/lists/*

COPY . /go/src

WORKDIR /go/src
RUN go build -o speedtest-cli speedtest.go

CMD ["/go/src/speedtest-cli", "-bytes", "-id", "raspi3", "-host", "dockerhub.us", "-port", "7676", "-server", "10546"]

